=== KonradHoeffner/pfannkuchenedit/szene.dtd
<!ENTITY % vector3d "x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED">
<!ENTITY % farbe3d "r CDATA #REQUIRED g CDATA #REQUIRED b CDATA #REQUIRED">

<!ELEMENT szene (triangulation, fenster,raumteilung,kamera,beleuchtung) >

<!ELEMENT triangulation EMPTY>

<!ATTLIST triangulation src CDATA #REQUIRED>

<!ELEMENT fenster EMPTY>

<!ATTLIST fenster
breite CDATA #REQUIRED
hoehe CDATA #REQUIRED
>

<!ELEMENT raumteilung EMPTY>

<!ATTLIST raumteilung
unterteilung CDATA #REQUIRED
>

<!ELEMENT kamera (position,ziel,fovy)>

<!ELEMENT position EMPTY >
<!ELEMENT ziel EMPTY >
<!ELEMENT fovy EMPTY >

<!ATTLIST position %vector3d;>
<!ATTLIST ziel %vector3d;>
<!ATTLIST fovy winkel CDATA #REQUIRED>

<!ELEMENT beleuchtung (hintergrundfarbe,ambientehelligkeit,abschwaechung,lichtquelle+)>

<!ELEMENT hintergrundfarbe EMPTY >
<!ELEMENT ambientehelligkeit EMPTY >
<!ELEMENT abschwaechung EMPTY >
<!ELEMENT lichtquelle (position,farbe)>

<!ATTLIST hintergrundfarbe %farbe3d;>
<!ATTLIST ambientehelligkeit %farbe3d;>
<!ATTLIST abschwaechung 
konstant CDATA #REQUIRED
linear CDATA #REQUIRED
quadratisch CDATA #REQUIRED
>

<!ELEMENT farbe EMPTY >

<!ATTLIST position %vector3d;>
<!ATTLIST farbe %farbe3d;>

=== KonradHoeffner/pfannkuchenedit/examples/julianszene.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE szene SYSTEM "szene.dtd">
<szene><triangulation src="neuetriangulationexporttest.xml"/><fenster breite="400" hoehe="400"/><raumteilung unterteilung="2"/><kamera><position x="-1.0677966101694925" y="3.490992444984848" z="5.506475905981304"/><ziel x="-1.8084295343649712" y="-0.0243461903875941" z="-9.596300565590477"/><fovy winkel="45.0"/></kamera><beleuchtung><!-- Lichteigenschaften !--><hintergrundfarbe b="0.5" g="0.2" r="0.2"/><ambientehelligkeit b="1" g="1" r="1"/><abschwaechung konstant="1" linear="0" quadratisch="1"/><!-- Lichtquellen !--><lichtquelle><position x="-1.5762711864406795" y="3.203389830508472" z="0.42372881355932296"/><farbe b="1.0" g="1.0" r="1.0"/></lichtquelle></beleuchtung></szene>

=== KonradHoeffner/pfannkuchenedit/vorlageszene.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE szene SYSTEM "szene.dtd">
<szene>

<triangulation src="neuetriangulationexporttest.xml"/>
<fenster breite="400" hoehe="400" />
<raumteilung unterteilung="2"/>
<kamera>
<position x="0" y="0" z="10"/>
<ziel x="0" y="0" z="0"/>
<fovy winkel="45" />
</kamera>

<beleuchtung>

<!-- Lichteigenschaften !-->

<hintergrundfarbe r="0.2" g="0.2" b="0.5"/>
<ambientehelligkeit r="1" g="1" b="1"/>
<abschwaechung konstant="1" linear="0" quadratisch="1" />

<!-- Lichtquellen !-->

</beleuchtung>

</szene>
