=== KonradHoeffner/pfannkuchenedit/examples/triangulation.dtd
<!ELEMENT triangulation (material+, dreieck+) >
<!ELEMENT material (ambient,diffus,spiegelnd) >

<!ATTLIST material 
name ID #REQUIRED
glanzwert CDATA #REQUIRED
>

<!ENTITY % vector3d "x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED">
<!ENTITY % farbe "r CDATA #REQUIRED g CDATA #REQUIRED b CDATA #REQUIRED a CDATA #REQUIRED">

<!ELEMENT ambient EMPTY >
<!ELEMENT diffus EMPTY >
<!ELEMENT spiegelnd EMPTY >

<!ATTLIST ambient %farbe;>
<!ATTLIST diffus %farbe;>
<!ATTLIST spiegelnd %farbe;>

<!ELEMENT dreieck ( punkt1, punkt2,punkt3,normale1,normale2,normale3) >

<!ATTLIST dreieck material IDREF #REQUIRED>

<!ELEMENT punkt1 EMPTY >
<!ELEMENT punkt2 EMPTY >
<!ELEMENT punkt3 EMPTY >
<!ELEMENT normale1 EMPTY >
<!ELEMENT normale2 EMPTY >
<!ELEMENT normale3 EMPTY >

<!ATTLIST punkt1 %vector3d;>
<!ATTLIST punkt2 %vector3d;>
<!ATTLIST punkt3 %vector3d;>
<!ATTLIST normale1 %vector3d;>
<!ATTLIST normale2 %vector3d;>
<!ATTLIST normale3 %vector3d;>

=== KonradHoeffner/pfannkuchenedit/triangulationexporttest_low.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE triangulation SYSTEM "triangulation.dtd">
<!--xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="triangulation.xsd" --><triangulation><material glanzwert="1" name="blau"><ambient a="0.0" b="0.5019607843137255" g="0.0" r="0.0"/><diffus a="0.0" b="0.5019607843137255" g="0.0" r="0.0"/><spiegelnd a="0.0" b="0.5019607843137255" g="0.0" r="0.0"/></material><material glanzwert="1" name="gelb"><ambient a="0.5019607843137255" b="0.0" g="0.5019607843137255" r="0.5019607843137255"/><diffus a="0.5019607843137255" b="0.5019607843137255" g="0.5019607843137255" r="0.5019607843137255"/><spiegelnd a="0.5019607843137255" b="0.0" g="0.5019607843137255" r="0.5019607843137255"/></material><material glanzwert="5" name="rot"><ambient a="0.5019607843137255" b="0.0" g="0.0" r="0.5019607843137255"/><diffus a="0.5019607843137255" b="0.0" g="0.0" r="0.5019607843137255"/><spiegelnd a="0.5019607843137255" b="0.0" g="0.0" r="0.5019607843137255"/></material><dreieck material="gelb"><punkt1 x="-1.8461001423639807" y="0.7133201039284207" z="0.0"/><punkt2 x="-0.21191351297670916" y="0.7047964214601861" z="1.6342088583871235"/><punkt3 x="-0.4628157021387081" y="1.5933820926284752" z="0.0"/><normale1 x="-0.9748782687456208" y="3.551611213556191" z="0.777802752311279"/><normale2 x="0.5807060760635177" y="3.543497509301566" z="0.777802752311279"/><normale3 x="-0.9748782687456208" y="3.551611213556191" z="0.777802752311279"/></dreieck><dreieck material="gelb"><punkt1 x="-0.21191351297670916" y="0.7047964214601861" z="1.6342088583871235"/><punkt2 x="-0.20728572962433314" y="1.5920492850362078" z="0.2555334483571086"/><punkt3 x="-0.4628157021387081" y="1.5933820926284752" z="0.0"/><normale1 x="0.5807060760635177" y="3.543497509301566" z="0.777802752311279"/><normale2 x="-0.19960158256928898" y="3.0652776018343033" z="1.4639400490509558"/><normale3 x="-0.9748782687456208" y="3.551611213556191" z="0.777802752311279"/></dreieck><dreieck material="gelb"><punkt1 x="-0.4628157021387081" y="1.5933820926284752" z="0.0"/><punkt2 x="-0.20728572962433314" y="1.5920492850362078" z="0.2555334483571086"/><punkt3 x="-0.559989956386691" y="2.036537926739134" z="0.0"/><normale1 x="-0.9748782687456208" y="3.551611213556191" z="0.777802752311279"/><normale2 x="-0.19960158256928898" y="3.0652776018343033" z="1.4639400490509558"/><normale3 x="-1.3459503447891246" y="2.088444848792129" z="1.1412382193690185"/></dreieck><dreieck material="gelb"><punkt1 x="-0.20728572962433314" y="1.5920492850362078" z="0.2555334483571086"/><punkt2 x="-0.20497699896807683" y="2.034686230202931" z="0.35501778647720267"/><punkt3 x="-0.559989956386691" y="2.036537926739134" z="0.0"/><normale1 x="-0.19960158256928898" y="3.0652776018343033" z="1.4639400490509558"/><normale2 x="-0.2079255687237052" y="1.469377364179258" z="1.3836198790217344"/><normale3 x="-1.3459503447891246" y="2.088444848792129" z="1.1412382193690185"/></dreieck><dreieck material="gelb"><punkt1 x="-0.559989956386691" y="2.036537926739134" z="0.0"/><punkt2 x="-0.20497699896807683" y="2.034686230202931" z="0.35501778647720267"/><punkt3 x="-0.9855191450614071" y="2.4134789578036666" z="0.0"/><normale1 x="-1.3459503447891246" y="2.088444848792129" z="1.1412382193690185"/><normale2 x="-0.2079255687237052" y="1.469377364179258" z="1.3836198790217344"/><normale3 x="-1.1081268449879975" y="1.317624334211631" z="0.8993975202398803"/></dreieck><dreieck material="gelb"><punkt1 x="-0.20497699896807683" y="2.034686230202931" z="0.35501778647720267"/><punkt2 x="-0.20302255851171125" y="2.409397568128653" z="0.7825072304481306"/><punkt3 x="-0.9855191450614071" y="2.4134789578036666" z="0.0"/><normale1 x="-0.2079255687237052" y="1.469377364179258" z="1.3836198790217344"/><normale2 x="-0.20983662163986636" y="1.102984418960955" z="1.0690670763285859"/><normale3 x="-1.1081268449879975" y="1.317624334211631" z="0.8993975202398803"/></dreieck><dreieck material="gelb"><punkt1 x="-0.9855191450614071" y="2.4134789578036666" z="0.0"/><punkt2 x="-0.20302255851171125" y="2.409397568128653" z="0.7825072304481306"/><punkt3 x="-2.8095647550598746" y="3.9868075721839045" z="0.0"/><normale1 x="-1.1081268449879975" y="1.317624334211631" z="0.8993975202398803"/><normale2 x="-0.20983662163986636" y="1.102984418960955" z="1.0690670763285859"/><normale3 x="-1.0986594735032176" y="1.3010481609943745" z="0.8898438197732698"/></dreieck><dreieck material="gelb"><punkt1 x="-0.20302255851171125" y="2.409397568128653" z="0.7825072304481306"/><punkt2 x="-0.1948661480402399" y="3.9731696802347294" z="2.614734173419398"/><punkt3 x="-2.8095647550598746" y="3.9868075721839045" z="0.0"/><normale1 x="-0.20983662163986636" y="1.102984418960955" z="1.0690670763285859"/><normale2 x="-1.0986594735032176" y="1.3010481609943745" z="0.8898438197732698"/><normale3 x="-1.0986594735032176" y="1.3010481609943745" z="0.8898438197732698"/></dreieck><dreieck material="gelb"><punkt1 x="-0.21191351297670916" y="0.7047964214601861" z="1.6342088583871235"/><punkt2 x="1.4222731164105624" y="0.6962727389919514" z="0.0"/><punkt3 x="-0.20728572962433314" y="1.5920492850362078" z="0.2555334483571086"/><normale1 x="0.5807060760635177" y="3.543497509301566" z="0.777802752311279"/><normale2 x="0.5807060760635177" y="3.543497509301566" z="-0.777802752311279"/><normale3 x="-0.19960158256928898" y="3.0652776018343033" z="1.4639400490509558"/></dreieck><dreieck material="gelb"><punkt1 x="1.4222731164105624" y="0.6962727389919514" z="0.0"/><punkt2 x="0.048244242890041866" y="1.5907164774439404" z="0.0"/><punkt3 x="-0.20728572962433314" y="1.5920492850362078" z="0.2555334483571086"/><normale1 x="0.5807060760635177" y="3.543497509301566" z="-0.777802752311279"/><normale2 x="1.2643185535293129" y="3.057642004911302" z="0.0"/><normale3 x="-0.19960158256928898" y="3.0652776018343033" z="1.4639400490509558"/></dreieck><dreieck material="gelb"><punkt1 x="-0.20728572962433314" y="1.5920492850362078" z="0.2555334483571086"/><punkt2 x="0.048244242890041866" y="1.5907164774439404" z="0.0"/><punkt3 x="-0.20497699896807683" y="2.034686230202931" z="0.35501778647720267"/><normale1 x="-0.19960158256928898" y="3.0652776018343033" z="1.4639400490509558"/><normale2 x="1.2643185535293129" y="3.057642004911302" z="0.0"/><normale3 x="-0.2079255687237052" y="1.469377364179258" z="1.3836198790217344"/></dreieck><dreieck material="gelb"><punkt1 x="0.048244242890041866" y="1.5907164774439404" z="0.0"/><punkt2 x="0.1500359584505373" y="2.0328345336667284" z="0.0"/><punkt3 x="-0.20497699896807683" y="2.034686230202931" z="0.35501778647720267"/><normale1 x="1.2643185535293129" y="3.057642004911302" z="0.0"/><normale2 x="1.1756754898847583" y="1.4621607000148267" z="0.0"/><normale3 x="-0.2079255687237052" y="1.469377364179258" z="1.3836198790217344"/></dreieck><dreieck material="gelb"><punkt1 x="-0.20497699896807683" y="2.034686230202931" z="0.35501778647720267"/><punkt2 x="0.1500359584505373" y="2.0328345336667284" z="0.0"/><punkt3 x="-0.20302255851171125" y="2.409397568128653" z="0.7825072304481306"/><normale1 x="-0.2079255687237052" y="1.469377364179258" z="1.3836198790217344"/><normale2 x="1.1756754898847583" y="1.4621607000148267" z="0.0"/><normale3 x="-0.20983662163986636" y="1.102984418960955" z="1.0690670763285859"/></dreieck><dreieck material="gelb"><punkt1 x="0.1500359584505373" y="2.0328345336667284" z="0.0"/><punkt2 x="0.5794740280379849" y="2.4053161784536385" z="0.0"/><punkt3 x="-0.20302255851171125" y="2.409397568128653" z="0.7825072304481306"/><normale1 x="1.1756754898847583" y="1.4621607000148267" z="0.0"/><normale2 x="0.8592159129171708" y="1.0974083946669353" z="0.0"/><normale3 x="-0.20983662163986636" y="1.102984418960955" z="1.0690670763285859"/></dreieck><dreieck material="gelb"><punkt1 x="-0.20302255851171125" y="2.409397568128653" z="0.7825072304481306"/><punkt2 x="0.5794740280379849" y="2.4053161784536385" z="0.0"/><punkt3 x="-0.1948661480402399" y="3.9731696802347294" z="2.614734173419398"/><normale1 x="-0.20983662163986636" y="1.102984418960955" z="1.0690670763285859"/><normale2 x="0.8592159129171708" y="1.0974083946669353" z="0.0"/><normale3 x="-1.0986594735032176" y="1.3010481609943745" z="0.8898438197732698"/></dreieck><dreieck material="gelb"><punkt1 x="0.5794740280379849" y="2.4053161784536385" z="0.0"/><punkt2 x="2.419832458979395" y="3.959531788285554" z="0.0"/><punkt3 x="-0.1948661480402399" y="3.9731696802347294" z="2.614734173419398"/><normale1 x="0.8592159129171708" y="1.0974083946669353" z="0.0"/><normale2 x="0.681003958197383" y="1.2917656924443581" z="0.8898438197732698"/><normale3 x="-1.0986594735032176" y="1.3010481609943745" z="0.8898438197732698"/></dreieck><dreieck material="gelb"><punkt1 x="1.4222731164105624" y="0.6962727389919514" z="0.0"/><punkt2 x="-0.21191351297670916" y="0.7047964214601861" z="-1.6342088583871235"/><punkt3 x="0.048244242890041866" y="1.5907164774439404" z="0.0"/><normale1 x="0.5807060760635177" y="3.543497509301566" z="-0.777802752311279"/><normale2 x="-0.9748782687456208" y="3.551611213556191" z="-0.777802752311279"/><normale3 x="1.2643185535293129" y="3.057642004911302" z="0.0"/></dreieck><dreieck material="gelb"><punkt1 x="-0.21191351297670916" y="0.7047964214601861" z="-1.6342088583871235"/><punkt2 x="-0.20728572962433314" y="1.5920492850362078" z="-0.2555334483571086"/><punkt3 x="0.048244242890041866" y="1.5907164774439404" z="0.0"/><normale1 x="-0.9748782687456208" y="3.551611213556191" z="-0.777802752311279"/><normale2 x="-0.19960158256928898" y="3.0652776018343033" z="-1.4639400490509558"/><normale3 x="1.2643185535293129" y="3.057642004911302" z="0.0"/></dreieck><dreieck material="gelb"><punkt1 x="0.048244242890041866" y="1.5907164774439404" z="0.0"/><punkt2 x="-0.20728572962433314" y="1.5920492850362078" z="-0.2555334483571086"/><punkt3 x="0.1500359584505373" y="2.0328345336667284" z="0.0"/><normale1 x="1.2643185535293129" y="3.057642004911302" z="0.0"/><normale2 x="-0.19960
